import Header from "../layout/header/header";
import Footer from "../layout/footer/footer";
import { vazir } from "../fonts/font";
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={vazir.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
