import Header from "../layout/header/header";
import Footer from "../layout/footer/footer";
import { vazir } from "../fonts/font";
import "./globals.css"



async function getSetting() {
  try {
    const data = await fetch("http://localhost/payam/-/server/getSettings/", { cache: "force-cache" })
      .then(res => res.json())

    return data
  } catch (err) {
    console.log(err);
  }
}


const setting = await getSetting()
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={vazir.className}>
        <Header />
        {children}
        <Footer footerText={setting.footer} />
      </body>
    </html>
  );
}
